image: docker:stable

services:
  - docker:dind

before_script:
 - docker info

build:
  only:
    - main
  before_script:
    - docker login registry.gitlab.com -u ruana-nadalia.ban -p 3j9828DutEyz_oupiuzs
  script:    
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .    
    - docker push ${CI_REGISTRY_IMAGE}:latest    
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build