name: Docker Image CI  # Workflow pentru construirea imaginii Docker

on:
  push:
    branches: [ "main" ]  # La fiecare push pe ramura principală
  pull_request:
    branches: [ "main" ]  # La fiecare PR pe ramura principală

jobs:
  build:
    runs-on: ubuntu-latest  # Folosește Ubuntu pentru build

    permissions:
      contents: read  # Permite citirea codului
      packages: write  # Permite încărcarea imaginilor

    steps:
    - uses: actions/checkout@v3  # Adaugă codul din repository

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2  # Logare în GHCR
      with:
        registry: ghcr.io  # Registry-ul GitHub
        username: ${{ github.actor }}  # Utilizatorul GitHub
        password: ${{ secrets.GITHUB_TOKEN }}  # Token-ul pentru autentificare

    - name: Build the Docker image
    
      id: docker_build
      
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository }}/proiect-bst  # Numele imaginii
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest  # Construim imaginea
        docker push $IMAGE_NAME:latest  # Împingem imaginea în GHCR
